server:
  port: 8081
spring:
  application:
    name: product
#  main:
#    banner-mode: off

#logging:
#  level:
#    root: debug
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anisa
    username: root
    password: amir31329
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true