server:
  port: 8084
spring:
  application:
    name: notification
#  main:
#    banner-mode: off

#logging:
#  level:
#    root: debug
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anisa
    username: root
    password: amir31329
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    registry-fetch-interval-seconds: 5