server:
  port: 7070
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    registry-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enable: true
  info:
    env:
      enable: true
info:
  app:
    name: "gateway"
    description: "test"
    version: "1.0"

resilience4j.circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-on-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
